services:
  - type: web
    name: todo-adventure-backend
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: STATIC_DIR
        value: ./frontend/out
      - key: TODO_DB_PATH
        value: ./backend/todos.db
      - key: TODO_PHOTOS_PATH
        value: ./backend/photos
    plan: starter